oerindex:
  hosts:
    192.168.98.115:
        ansible_ssh_user: vagrant
        ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
        
example:
  hosts:
    192.168.98.115:
      oerindex_host: 192.168.98.115
      oerindex_db:
        name: oerindex_db
        user: oerindex
        password: oerindexpw
      elasticsearch_elastic_password: changeme
      elasticsearch_bootstrap_password: bootstrap
      elasticsearch_builtin_users:
        - name: apm_system
          password: changeme
        - name: beats_system
          password: changeme
        - name: logstash_system
          password: changeme
        - name: kibana_system
          password: changeme
        - name: remote_monitoring_user
          password: changeme
      # logstash-user that writes to the oer-index
      elasticsearch_oersi_logstash_username: oersi_logstash
      elasticsearch_oersi_logstash_password: ch@ngeMe
      # user with read-only access to oer-index
      elasticsearch_oersi_viewer_username: oersi_viewer
      elasticsearch_oersi_viewer_password: ch@ngeMe
      oerindex_backend_oermetadata_manage_user: test
      oerindex_backend_oermetadata_manage_password: test

      oerindex_frontend_custom_style_css: '../doc/gitlab-config-example/frontend/style-override.css'
      
      kibana_install: true
      
      matomo_install: true
      matomo_superuser_name: admin
      matomo_superuser_password: changeme
      matomo_superuser_mail: xyz@example.org
      matomo_dbname: matomo
      matomo_dbuser: matomo
      matomo_dbpassword: changeme
