application_name: "OERSI"

search_index_metadata_schema_artifact_url: https://gitlab.com/oersi/oersi-schema/-/jobs/artifacts/main/download?job=deploy
oerindex_etl_artifact_url: https://gitlab.com/oersi/oersi-etl/-/jobs/artifacts/master/download?job=deploy
oerindex_import_scripts_artifact_url: https://gitlab.com/oersi/oersi-import-scripts/-/jobs/artifacts/master/download?job=deploy

oerindex_etl_configfiles: []
oerindex_import_scripts_enabled_sources_py:  # list of enabled python imports (will be imported scheduled)
  - twillo
