---
collections:
- source: https://gitlab.com/oersi/oersi-setup/-/jobs/artifacts/test-inclusion-in-another-vagrant-playbook/raw/search_index-setup.tar.gz?job=deploy
  type: url
  name: search_index.setup
