---
- name: Check if the oer_index.conf exists
  stat: path={{ base_dir }}/conf/oer_index.conf
  register: oer_index_conf_file_stat
  
- name: Get current installed index version
  shell: 'grep "OER_INDEX_VERSION=" {{ base_dir }}/conf/oer_index.conf | cut -d"=" -f2'
  when: oer_index_conf_file_stat.stat.exists
  register: current_installed_index_version

- name: Check status of synonym-feature
  shell: 'grep "OER_INDEX_FEATURE_SYNONYM=" {{ base_dir }}/conf/oer_index.conf | cut -d"=" -f2'
  when: oer_index_conf_file_stat.stat.exists
  register: current_status_feature_synonym

- name: Determine if index update is necessary
  set_fact:
    process_index_update: "{{ not oer_index_conf_file_stat.stat.exists or (current_installed_index_version.stdout | int) != elasticsearch_oer_index_version or current_status_feature_synonym.stdout != (oerindex_features_use_synonyms | string) }}"

- name: Create or recreate index
  become_user: "{{ oersi_user }}"
  command: "{{ base_dir }}/bin/recreate-index.sh"
  when: process_index_update
