stages:
  - deploy

.deploy_job:
  image: willhallonline/ansible:2.13-alpine-3.16
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | base64 -d | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ansible-galaxy install -r requirements.yml
    - ansible-playbook -v -i ${INVENTORY_FILE} ${PLAYBOOK}

#scheduled deploy to Develop:
#  variables:
#    INVENTORY_FILE: inventory_DEV.yml
#    PLAYBOOK: search_index.setup.system
#  extends: .deploy_job
#  only:
#    - schedules

deploy to Develop:
  variables:
    INVENTORY_FILE: inventory_DEV.yml
    PLAYBOOK: search_index.setup.system
  extends: .deploy_job
  only:
    - master
  when: manual

Develop Backend Deployment:
  variables:
    INVENTORY_FILE: inventory_DEV.yml
    PLAYBOOK: search_index.setup.backend
  extends: .deploy_job
  only:
    - master
  when: manual

Develop ETL Deployment:
  variables:
    INVENTORY_FILE: inventory_DEV.yml
    PLAYBOOK: search_index.setup.etl
  extends: .deploy_job
  only:
    - master
  when: manual

Develop Frontend Deployment:
  variables:
    INVENTORY_FILE: inventory_DEV.yml
    PLAYBOOK: search_index.setup.frontend
  extends: .deploy_job
  only:
    - master
  when: manual

deploy to Test:
  variables:
    INVENTORY_FILE: inventory_TEST.yml
    PLAYBOOK: search_index.setup.system
  extends: .deploy_job
  only:
    - master
  when: manual
