- hosts: all
  tasks:
    - name: checkout oersi-setup locally
      git:
        repo: 'https://gitlab.com/oersi/oersi-setup.git'
        dest: '{{ inventory_dir }}/oersi-setup'
        force: yes
        version: '{{ oersi_setup_branch }}'
      delegate_to: localhost
    
    - name: install required ansible-galaxy roles
      shell: ansible-galaxy install -r oersi-setup/requirements.yml
      delegate_to: localhost
