---
- name: Ensures config-dir exists
  file: path='{{ oerindex_backend_configdir }}/custom' state=directory

- name: copy custom config-files
  template:
    src: "custom-config.json.j2"
    dest: "{{ oerindex_backend_configdir }}/custom/custom-config.json"
  register: copy_config_result

- name: update config
  block:
    - set_fact:
        oerindex_backend_custom_config_import: "{{ copy_config_result.changed }}"

    - name: Make sure Tomcat is running before proceeding.
      wait_for:
        host: "localhost"
        port: "{{ tomcat_port }}"
        delay: 1
        timeout: 30
      when: oerindex_backend_custom_config_import

    - name: "import custom config"
      uri:
        url: '{{ oerindex_backend_internal_api_base_url }}/metadata-config'
        method: POST
        body_format: json
        status_code: 200
        timeout: 60
        headers:
          Accept: 'application/json'
        user: '{{ oerindex_backend_oermetadata_manage_user }}'
        password: '{{ oerindex_backend_oermetadata_manage_password }}'
        force_basic_auth: yes
        src: '{{ oerindex_backend_configdir }}/custom/custom-config.json'
        remote_src: yes
      retries: 3
      delay: 5
      when: oerindex_backend_custom_config_import
  rescue:
    - name: remove custom config-files
      file:
        path: "{{ oerindex_backend_configdir }}/custom/custom-config.json"
        state: absent
    - fail:
        msg: "custom config cannot be updated"
