---
- name: Ensures inst-dir exists
  file: path='{{ oerindex_backend_downloaddir }}' state=directory

- name: Ensure unzip is present
  package:
    name: ["unzip"]
  become: yes
  tags:
    - root-task

- name: find war-files in download directory
  find:
    paths: "{{ oerindex_backend_downloaddir }}"
    patterns: oersi-backend*.war
  register: oersi_existing_war_find_result

- name: remove war-files from download dir
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ oersi_existing_war_find_result.files }}"

- name: download OER search index backend
  get_url:
    url: "{{ oerindex_backend_artifact_url }}"
    force: yes
    dest: "{{ oerindex_backend_downloaddir }}/"
  register: oersi_backend_download_result

- name: set facts about downloaded artifact
  set_fact:
    backend_artifact_path: "{{ oersi_backend_download_result.dest }}"

- name: extract OER search index backend
  unarchive:
    remote_src: yes
    src: '{{ backend_artifact_path }}'
    dest: "{{ oerindex_backend_downloaddir }}"
    extra_opts:
      - -j
  when: backend_artifact_path.endswith('.zip')

- name: find war-files in download directory
  find:
    paths: "{{ oerindex_backend_downloaddir }}"
    patterns: oersi-backend*.war
  register: oersi_war_find_result

- name: stop tomcat
  shell: '{{ tomcat_stop_command }}'

- name: undeploy backend from tomcat
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ tomcat_home }}/webapps/oersi.war"
    - "{{ tomcat_home }}/webapps/oersi"
    - "{{ tomcat_home }}/work/Catalina/localhost/oersi"
  
- name: Ensures config-dir exists
  file: path='{{ oerindex_backend_configdir }}' state=directory

- name: copy config-files
  template:
    src: "{{ item }}"
    dest: "{{ oerindex_backend_configdir }}/"
  with_items:
    - "logback.xml"
    - "oersi.properties"

- name: Ensures tomcat-config-dir exists
  file: path='{{ tomcat_home }}/conf/Catalina/localhost' state=directory

- name: copy context.xml.default
  template:
    src: "context.xml.default"
    dest: "{{ tomcat_home }}/conf/Catalina/localhost/context.xml.default"

- name: copy war-files to tomcat
  copy:
    src: "{{ item.path }}"
    dest: "{{tomcat_home}}/webapps/oersi.war"
    remote_src: yes
  with_items:
    - "{{ oersi_war_find_result.files }}"

- name: start tomcat
  shell: '{{tomcat_start_command}}'

- include: import-labels.yml
- include: vocab-scheme.yml
