---
- name: Install curl and jq
  become: yes
  package:
    name: ["jq", "curl"]
    state: present
  
- name: Ensures dirs exist
  file: path='{{ item }}' state=directory
  loop:
    - '{{ base_dir }}/bin'
    - '{{ base_dir }}/conf'

- name: Add oer_index_access
  become: true  # workaround for update of old configuration before 04/2021
  template:
    src: "oer_index_access.j2"
    dest: "{{ base_dir }}/conf/oer_index_access"
    owner: "{{ oersi_user }}"  # workaround for update of old configuration before 04/2021
    group: "{{ oersi_user }}"  # workaround for update of old configuration before 04/2021
    mode: 0400

- name: Add oer_backend_access
  template:
    src: "oer_backend_access.j2"
    dest: "{{ base_dir }}/conf/oer_backend_access"
    mode: 0400

- name: Add scripts
  template:
    src: "{{ item }}"
    dest: "{{ base_dir }}/bin/{{ item | regex_replace('.j2$', '') }}"
    mode: 0700
  loop:
    - analyze-requests.py
    - create-new-index-and-rebuild.sh.j2
    - create-statistics.sh.j2
    - create-synonyms-file.sh.j2
    - recreate-index.sh.j2
    - reload-search_analyzer.sh.j2
    - reset-backend-metadata.sh.j2
    - show-versions.sh.j2
    - update-index-alias.sh.j2

- include: delete-outdated-data.yml

- include: sitemap.yml
- include: monitoring.yml

- name: Delete unused scripts
  file:
    path: "{{ base_dir }}/bin/{{ item }}"
    state: absent
  loop:
    - reset-sql-oerdata.sh
