---
- name: Add create-sitemap.sh.j2
  template:
    src: "create-sitemap.sh.j2"
    dest: "{{ base_dir }}/bin/create-sitemap.sh"
    mode: 0544

- name: Cleanup old unused sitemap data oersi sudoers
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/sudoers.d/oersi"
    - "{{ base_dir }}/.sitemaptool"