---
# Use oersi-etl as metadata harvester

- name: Ensures inst-dir exists
  file: path='{{ oerindex_etl_downloaddir }}' state=directory

- name: Ensures output-dir exists
  file: path='{{ oerindex_etl_outputdir }}' state=directory

- name: download OER search index ETL
  get_url:
    url: "{{ oerindex_etl_artifact_url }}"
    force: yes
    dest: "{{ oerindex_etl_downloaddir }}/oersi-etl.zip"

- name: Ensure unzip is present
  package:
    name: ["unzip"]
  become: yes
  tags:
    - root-task

- name: extract OER search index ETL
  unarchive:
    remote_src: yes
    src: '{{ oerindex_etl_downloaddir }}/oersi-etl.zip'
    dest: "{{ oerindex_etl_downloaddir }}"

- name: Ensures config-dir exists
  file: path='{{ oerindex_etl_configdir }}' state=directory

- name: Ensures config-enabled-dir exists
  file: path='{{ oerindex_etl_configdir }}-enabled' state=directory
  
- name: Create oersi.properties
  template:
    src: "oersi.properties.j2"
    dest: "{{ oerindex_etl_configdir }}/oersi.properties"
    mode: '600'

- name: Create log4j.properties
  template:
    src: "log4j.properties.j2"
    dest: "{{ oerindex_etl_configdir }}/log4j.properties"

- name: Create etl wrapper script
  template:
    src: "etl.sh.j2"
    dest: "{{ oerindex_etl_downloaddir }}/etl.sh"
    mode: 0700

- name: Copy oersi-etl custom config files
  copy:
    src: "{{ item }}"
    dest: "{{ oerindex_etl_configdir }}/{{ item | basename }}"
    mode: 'preserve'
  loop: '{{ oerindex_etl_customfiles | default([], true) }}'

- name: Find current config enabled files
  find: path='{{ oerindex_etl_configdir }}-enabled' file_type=link
  register: oerindex_etl_config_enabled_files

- name: Remove current config enabled files
  file: state=absent path='{{ item.path }}'
  with_items: '{{ oerindex_etl_config_enabled_files.files }}'

- name: Create config enabled files
  file:
    state: link
    src: '{{ oerindex_etl_configdir }}/{{ item | basename }}'
    path: '{{ oerindex_etl_configdir }}-enabled/{{ item | basename }}'
  loop: '{{ (oerindex_etl_configfiles | default([], true)) + (oerindex_etl_customfiles | default([], true)) }}'

- name: Extract, transform, and load some example OER sources
  command:
    cmd: './build/install/oersi-etl/bin/oersi-etl {{ oerindex_etl_configdir }}/{{ item }} {{ oerindex_etl_configdir }}/oersi.properties'
    chdir: '{{ oerindex_etl_downloaddir }}'
  loop: '{{ oerindex_import_example_sources | default([], true) }}'
  when: oerindex_import_example_sources_immediately

- name: Configure cron schedule - Extract, transform, and load OER sources
  cron:
    name: "ETL OER sources"
    hour: '{{ oerindex_import_sources_schedule_hour }}'
    minute: '{{ oerindex_import_sources_schedule_minute }}'
    job: '{{ oerindex_etl_downloaddir }}/etl.sh'
    state: '{{ oerindex_import_sources_schedule_state }}'

- include: monitoring.yml
- include: cleanup-logs.yml
