---
# Use oersi-etl as metadata harvester

- name: Install git
  become: yes
  package:
    name: [ "git" ]
    state: present
  tags:
  - root-task

# Problem with windows and copy-module -> use archive, should be moved to a separate project anyway
- name: Ensures inst-dir exists
  file: path='{{ oerindex_harvester_instdir }}' state=directory

- name: Copy OER metadata harvester setup
  copy:
    src: oersi-etl/
    dest: "{{ oerindex_harvester_instdir }}/"
    mode: 'preserve'

- name: Fix line endings for installer
  command:
    cmd: "sed -i 's/\r$//' install.sh"
    chdir: '{{ oerindex_harvester_instdir }}'

- name: Fix line endings for importer
  command:
    cmd: "sed -i 's/\r$//' import.sh"
    chdir: '{{ oerindex_harvester_instdir }}'

- name: Install oersi-etl dependencies
  command:
    cmd: '{{ oerindex_harvester_instdir }}/install.sh'
    chdir: '{{ oerindex_harvester_instdir }}'

- name: Extract, transform, and load some OER sources
  command:
    cmd: '{{ oerindex_harvester_instdir }}/import.sh {{ item }}'
    chdir: '{{ oerindex_harvester_instdir }}'
  with_items:
    - 'data/to-oersibackend'
