---
- name: Create monitoring-etl.sh
  template:
    src: "monitoring-etl.sh.j2"
    dest: "{{ base_dir }}/bin/monitoring-etl.sh"
    mode: 0700

- name: Remove deprecated schedule - ETL Monitoring
  cron:
    name: "ETL Monitoring"
    state: "absent"
