---
- name: Assure synonyms file exists
  file:
    path: "{{ elasticsearch_conf_dir }}/synonym.txt"
    state: touch
  when: oerindex_features_use_synonyms
  
# copy example just for first phase / tests - needs to be created / updated independently afterwards
- name: Copy synonyms file for TESTs
  copy:
    src: "{{ elasticsearch_synonyms_file }}"
    dest: "{{ elasticsearch_conf_dir }}/synonym.txt"
  when: oerindex_features_use_synonyms and elasticsearch_synonyms_file is defined and elasticsearch_synonyms_file is not none
  
- name: Configure mapping.
  template:
    src: "mapping.json"
    dest: "{{ base_dir }}/conf/mapping.json"
    owner: "{{ oersi_user }}"
    group: "{{ oersi_user }}"
    mode: 0644
  notify: restart logstash

- name: Update oer_data template
  uri:
    url: "{{elasticsearch_api_url}}/_index_template/oer_data"
    method: PUT
    body_format: json
    body: "{{ lookup('template','mapping.json') }}"
    status_code: 200
    user: "{{elasticsearch_elastic_username}}"
    password: "{{elasticsearch_elastic_password}}"
    force_basic_auth: yes
  no_log: true
