---

- name: Copy custom style-override.css
  become: true
  copy:
    src: '{{ oerindex_frontend_custom_style_css }}'
    dest: '{{ oerindex_frontend_public_dir }}/css/style-override.css'
    owner: "{{ oerindex_frontend_owner }}"
    group: "{{ oerindex_frontend_group }}"
  when: (oerindex_frontend_custom_style_css is defined) and (oerindex_frontend_custom_style_css != "") and (oerindex_frontend_custom_style_css is not none)

- name: Ensures the folder for the custom translations exists 
  become: true
  file: 
    path: "{{ oerindex_frontend_public_dir }}/locales/{{ item.language }}"
    state: directory
    owner: "{{ oerindex_frontend_owner }}"
    group: "{{ oerindex_frontend_group }}"
  loop: '{{ oerindex_frontend_custom_translations | default([], true) }}'

- name: Copy custom translations as override file
  become: true
  copy:
    src: '{{ item.path }}'
    dest: '{{ oerindex_frontend_public_dir }}/locales/{{ item.language }}/{{ item.path | basename }}.override'
    owner: "{{ oerindex_frontend_owner }}"
    group: "{{ oerindex_frontend_group }}"
  loop: '{{ oerindex_frontend_custom_translations | default([], true) }}'

- name: Merge custom translations into original translations and cleanup
  become: true
  shell:
    cmd: "((cat {{ item.path | basename }} ; cat {{ item.path | basename }}.override) | jq '. * input') > {{ item.path | basename }}.tmp && cp --no-preserve=ownership {{ item.path | basename }}.tmp {{ item.path | basename }} && rm {{ item.path | basename }}.tmp {{ item.path | basename }}.override"
    chdir: "{{ oerindex_frontend_public_dir }}/locales/{{ item.language }}"
  loop: '{{ oerindex_frontend_custom_translations | default([], true) }}'

- name: Ensures the folder for the custom footer  exists 
  become: true
  file:
    path: "{{ oerindex_frontend_public_dir }}/footer/{{ item.language }}"
    state: directory
    owner: "{{ oerindex_frontend_owner }}"
    group: "{{ oerindex_frontend_group }}"
  loop: '{{ oerindex_frontend_custom_footers | default([], true) }}'

- name: Copy custom footers 
  become: true
  copy:
    src: '{{ item.path }}'
    dest: '{{ oerindex_frontend_public_dir }}/footer/{{ item.language }}/{{ item.path | basename }}'
    owner: "{{ oerindex_frontend_owner }}"
    group: "{{ oerindex_frontend_group }}"
  loop: '{{ oerindex_frontend_custom_footers | default([], true) }}'

- name: Ensures the folder for the custom files exists
  become: true
  file:
    path: "{{ oerindex_frontend_public_dir }}/{{ item.destination | dirname }}"
    state: directory
    owner: "{{ oerindex_frontend_owner }}"
    group: "{{ oerindex_frontend_group }}"
  loop: '{{ oerindex_frontend_custom_files | default([], true) }}'

- name: Copy custom files
  become: true
  copy:
    src: '{{ item.source }}'
    dest: '{{ oerindex_frontend_public_dir }}/{{ item.destination}}'
    owner: "{{ oerindex_frontend_owner }}"
    group: "{{ oerindex_frontend_group }}"
  loop: '{{ oerindex_frontend_custom_files | default([], true) }}'
