---
- name: Ensures inst-dir exists
  file: path='{{ oerindex_frontend_instdir }}' state=directory

- name: download OER search index frontend
  get_url:
    url: "{{ oerindex_frontend_artifact_url }}"
    force: yes
    dest: "{{ oerindex_frontend_instdir }}.zip"

- name: Ensure unzip is present
  package:
    name: ["unzip"]
  become: yes
  tags:
    - root-task

- name: extract OER search index frontend
  unarchive:
    remote_src: yes
    src: '{{ oerindex_frontend_instdir }}.zip'
    dest: "{{ oerindex_frontend_instdir }}"

- name: Add configuration file.
  become: yes
  template:
    src: "config.js"
    dest: '{{ oerindex_frontend_instdir }}/build/config/config.js'

- name: Copy custom style-override.css
  copy:
    src: '{{ oerindex_frontend_custom_style_css }}'
    dest: '{{ oerindex_frontend_instdir }}/build/css/style-override.css'
  when: (oerindex_frontend_custom_style_css is defined) and (oerindex_frontend_custom_style_css != "") and (oerindex_frontend_custom_style_css is not none)

- name: Ensures the folder for the custom translations exists 
  file: path={{ oerindex_frontend_instdir }}/build/locales/{{ item.language }} state=directory
  loop: '{{ oerindex_frontend_custom_translations | default([], true) }}'

- name: Copy custom translations
  copy:
    src: '{{ item.path }}'
    dest: '{{ oerindex_frontend_instdir }}/build/locales/{{ item.language }}/{{ item.path | basename }}'
  loop: '{{ oerindex_frontend_custom_translations | default([], true) }}'
  
- name: Ensures the folder for the custom footer  exists 
  file: path={{ oerindex_frontend_instdir }}/build/footer/{{ item.language }} state=directory
  loop: '{{ oerindex_frontend_custom_footers | default([], true) }}'

- name: Copy custom footers 
  copy:
    src: '{{ item.path }}'
    dest: '{{ oerindex_frontend_instdir }}/build/footer/{{ item.language }}/{{ item.path | basename }}'
  loop: '{{ oerindex_frontend_custom_footers | default([], true) }}'

- name: Ensures the folder for the custom files exists
  file: path={{ oerindex_frontend_instdir }}/build/{{ item.destination | dirname }} state=directory
  loop: '{{ oerindex_frontend_custom_files | default([], true) }}'

- name: Copy custom files
  copy:
    src: '{{ item.source }}'
    dest: '{{ oerindex_frontend_instdir }}/build/{{ item.destination}}'
  loop: '{{ oerindex_frontend_custom_files | default([], true) }}'

- name: Check if sitemap.xml exists
  stat:
    path: "{{ oerindex_frontend_instdir }}/build/sitemap.xml"
  register: sitemap_stat_result

- name: Create sitemap, if it does not exist
  become: true
  command: "{{ base_dir }}/bin/create-sitemap.sh"
  when: not sitemap_stat_result.stat.exists

- name: adjust robots.txt
  lineinfile:
    path: '{{ oerindex_frontend_instdir }}/build/robots.txt'
    line: 'Sitemap: {{ oerindex_public_base_url }}{{ oerindex_public_base_path }}/sitemap.xml'
    regexp: '^Sitemap:.*$'
