---
- name: Ensures inst-dir exists
  file: path='{{ oerindex_frontend_instdir }}' state=directory

- name: download OER search index frontend
  get_url:
    url: "{{ oerindex_frontend_artifact_url }}"
    force: yes
    dest: "{{ oerindex_frontend_instdir }}.zip"

- name: Ensure unzip is present
  package:
    name: ["unzip"]
  become: yes
  tags:
  - root-task

- name: extract OER search index frontend
  unarchive:
    remote_src: yes
    src: '{{ oerindex_frontend_instdir }}.zip'
    dest: "{{ oerindex_frontend_instdir }}"

- name: Add configuration file.
  become: yes
  template:
    src: "config.js"
    dest: '{{ oerindex_frontend_instdir }}/build/config/config.js'

- name: Copy custom style-override.css
  copy:
    src: '{{ oerindex_frontend_custom_style_css }}'
    dest: '{{ oerindex_frontend_instdir }}/build/css/style-override.css'
  when: (oerindex_frontend_custom_style_css is defined) and (oerindex_frontend_custom_style_css != "") and (oerindex_frontend_custom_style_css is not none)

- name: Ensures the folder {{ oerindex_frontend_instdir }}/build/locales/{{oerindex_frontend_lang}} exists 
  file: path={{ oerindex_frontend_instdir }}/build/locales/{{oerindex_frontend_lang}} state=directory


- name: Copy custom translation.json
  copy:
    src: '{{ oerindex_frontend_custom_translation_file_path }}'
    dest: '{{ oerindex_frontend_instdir }}/build/locales/{{oerindex_frontend_lang}}/translation.json'
  when: (oerindex_frontend_custom_translation_file_path is defined) and (oerindex_frontend_custom_translation_file_path != "") and (oerindex_frontend_custom_translation_file_path is not none)
  
- name: Copy custom provider.json
  copy:
    src: '{{ oerindex_frontend_custom_provider_translation_file_path }}'
    dest: '{{ oerindex_frontend_instdir }}/build/locales/{{oerindex_frontend_lang}}/provider.json'
  when: (oerindex_frontend_custom_provider_translation_file_path is defined) and (oerindex_frontend_custom_provider_translation_file_path != "") and (oerindex_frontend_custom_provider_translation_file_path is not none)
  
- name: Copy custom lrt.json
  copy:
    src: '{{ oerindex_frontend_custom_lrt_translation_file_path }}'
    dest: '{{ oerindex_frontend_instdir }}/build/locales/{{oerindex_frontend_lang}}/lrt.json'
  when: (oerindex_frontend_custom_lrt_translation_file_path is defined) and (oerindex_frontend_custom_lrt_translation_file_path != "") and (oerindex_frontend_custom_lrt_translation_file_path is not none)
  
- name: Copy custom images for footer
  copy:
    src: '{{item[0]}}'
    dest: '{{ oerindex_frontend_instdir }}/build/{{item[1]}}'
  loop: '{{ oerindex_frontend_custom_images | default([], true) }}'

- name: Ensures the folder {{ oerindex_frontend_instdir }}/footer exists 
  file: path={{ oerindex_frontend_instdir }}/footer state=directory    
  
- name: Copy custom footer.html
  copy:
    src: '{{ oerindex_frontend_custom_footer_file_path }}'
    dest: '{{ oerindex_frontend_instdir }}/build/footer/footer.html'
  when: (oerindex_frontend_custom_footer_file_path is defined) and (oerindex_frontend_custom_footer_file_path != "") and (oerindex_frontend_custom_footer_file_path is not none)
