---
- name: Ensures inst-dir exists
  file: path='{{ oerindex_frontend_instdir }}' state=directory

- name: download OER search index frontend
  get_url:
    url: "{{ oerindex_frontend_artifact_url }}"
    force: yes
    dest: "{{ oerindex_frontend_instdir }}.zip"

- name: Ensure unzip is present
  package:
    name: ["unzip"]
  become: yes
  tags:
  - root-task

- name: extract OER search index frontend
  unarchive:
    remote_src: yes
    src: '{{ oerindex_frontend_instdir }}.zip'
    dest: "{{ oerindex_frontend_instdir }}"

- name: Add configuration file.
  become: yes
  template:
    src: "config.json"
    dest: '{{ oerindex_frontend_instdir }}/build/config/config.json'

- name: Add Css override file.
  become: yes
  template:
    src: "style-override.css"
    dest: '{{ oerindex_frontend_instdir }}/build/css/style-override.css'

- name: Ensures the folder {{ oerindex_frontend_instdir }}/build/locales/{{oerindex_frontend_lang}} exists 
  file: path={{ oerindex_frontend_instdir }}/build/locales/{{oerindex_frontend_lang}} state=directory

- name: Add translation file.
  become: yes
  template:
    src: "translation.json"
    dest: '{{ oerindex_frontend_instdir }}/build/locales/{{oerindex_frontend_lang}}/translation.json'

- name: Ensures the folder {{ oerindex_frontend_instdir }}/footer exists 
  file: path={{ oerindex_frontend_instdir }}/footer state=directory

- name: Add footer.html file.
  become: yes
  template:
    src: "footer.html"
    dest: '{{ oerindex_frontend_instdir }}/footer/footer.html'