---

- name: Checkout next frontend
  git:
    repo: "{{ oerindex_frontend_ssr_repo_url }}"
    dest: "{{ oerindex_frontend_instdir }}"
    version: "{{ oerindex_frontend_ssr_repo_version }}"
    force: yes

- name: Add configuration file.
  template:
    src: "env.j2"
    dest: "{{ oerindex_frontend_instdir }}/.env.local"

- include_tasks: common-config.yml
- include_tasks: sitemap.yml

- name: Add docker compose file
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ oerindex_frontend_instdir }}/docker-compose.yml"

- name: Create build.info
  shell:
    chdir: "{{ oerindex_frontend_instdir }}"
    cmd: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" > build.info && echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> build.info

- name: Build nextjs frontend
  command:
    chdir: "{{ oerindex_frontend_instdir }}"
    cmd: sg docker -c "docker compose build"

- name: Stop nextjs frontend
  command:
    chdir: "{{ oerindex_frontend_instdir }}"
    cmd: sg docker -c "docker compose down"

- name: Start nextjs frontend
  command:
    chdir: "{{ oerindex_frontend_instdir }}"
    cmd: sg docker -c "docker compose up -d"
