---
- name: Set sticky bit for webpage root dir
  become: true
  file:
    path: "{{ oerindex_frontend_instdir }}/build"
    owner: "{{ oerindex_frontend_owner }}"
    group: "{{ oerindex_frontend_group }}"
    state: touch
    mode: g+s

- name: Check if sitemap.xml exists
  stat:
    path: "{{ oerindex_frontend_instdir }}/build/sitemap.xml"
  register: sitemap_stat_result

- name: Create sitemap, if it does not exist
  command: "{{ base_dir }}/bin/create-sitemap.sh"
  when: not sitemap_stat_result.stat.exists

- name: adjust robots.txt
  become: true
  lineinfile:    
    path: '{{ oerindex_frontend_instdir }}/build/robots.txt'
    line: 'Sitemap: {{ oerindex_public_base_url }}{{ oerindex_public_base_path }}/sitemap.xml'
    regexp: '^Sitemap:.*$'
    owner: "{{ oerindex_frontend_owner }}"
    group: "{{ oerindex_frontend_group }}"
