---
- name: Ensure wget is present
  package:
    name: ["wget"]

- name: Delete old unused scripts
  file:
    path: "{{ base_dir }}/bin/{{ item }}"
    state: absent
  loop:
    - update-vocab-scheme.sh
    - build-vocab-parent-map.sh

- name: Ensures vocabs-dir exists
  become: true
  file:
    path: "{{ oerindex_frontend_vocabs_dir }}"
    owner: "{{ oerindex_frontend_owner }}"
    group: "{{ oerindex_frontend_group }}"
    state: directory

- name: "Build vars necessary for vocab updates"
  set_fact:
    search_index_frontend_vocab_scheme_updates: "{{ search_index_frontend_vocab_scheme_updates | default([], true) + [{'vocabName': item.vocabName, 'parentMapFile': oerindex_frontend_vocabs_dir + '/' + item.vocabName + '-parentMap.json'}] }}"
  loop: '{{ oerindex_frontend_hierarchical_vocab_filters | default([], true) }}'

- name: Create update-vocab-scheme script
  template:
    src: "update-vocab-scheme-frontend.sh.j2"
    dest: "{{ base_dir }}/bin/update-vocab-scheme-frontend.sh"
    mode: 0700

- name: Find default vocabs files
  find: path='{{ oerindex_frontend_public_dir }}/vocabs'
  register: vocabs_stat_result

- name: Init default files, if not exists yet
  copy:
    remote_src: true
    src: "{{ item.path }}"
    dest: "{{ oerindex_frontend_vocabs_dir }}"
    force: false
  loop: '{{ vocabs_stat_result.files }}'

- name: Update vocab-schemes immediately
  shell:
    cmd: "nohup {{ base_dir }}/bin/update-vocab-scheme-frontend.sh >/dev/null 2>&1 & sleep 1"

- name: Configure cron schedule - process vocab scheme updates
  cron:
    name: "Update vocab schemes for OERSI frontend"
    hour: "{{ oerindex_frontend_vocab_scheme_update_schedule_hour }}"
    minute: "0"
    job: "{{ base_dir }}/bin/update-vocab-scheme-frontend.sh >/dev/null 2>&1"
