---
- name: Ensures inst-dir exists
  file:
    path: "{{ oerindex_frontend_instdir }}"
    owner: "{{ oerindex_frontend_owner }}"
    group: "{{ oerindex_frontend_group }}"
    state: directory
    recurse: true # migration from old usage of ownership - migrate old files

- name: download OER search index frontend
  get_url:
    url: "{{ oerindex_frontend_artifact_url }}"
    force: yes
    dest: "{{ oerindex_frontend_instdir }}/frontend.zip"
    owner: "{{ oerindex_frontend_owner }}"
    group: "{{ oerindex_frontend_group }}"

- name: Ensure unzip is present
  package:
    name: ["unzip"]

- name: extract OER search index frontend
  unarchive:
    remote_src: yes
    src: '{{ oerindex_frontend_instdir }}/frontend.zip'
    dest: "{{ oerindex_frontend_instdir }}"
    owner: "{{ oerindex_frontend_owner }}"
    group: "{{ oerindex_frontend_group }}"

- name: Add configuration file.
  template:
    src: "config.js"
    dest: '{{ oerindex_frontend_instdir }}/build/config/config.js'
    owner: "{{ oerindex_frontend_owner }}"
    group: "{{ oerindex_frontend_group }}"

- name: Copy custom style-override.css
  copy:
    src: '{{ oerindex_frontend_custom_style_css }}'
    dest: '{{ oerindex_frontend_instdir }}/build/css/style-override.css'
    owner: "{{ oerindex_frontend_owner }}"
    group: "{{ oerindex_frontend_group }}"
  when: (oerindex_frontend_custom_style_css is defined) and (oerindex_frontend_custom_style_css != "") and (oerindex_frontend_custom_style_css is not none)

- name: Ensures the folder for the custom translations exists 
  file: 
    path: "{{ oerindex_frontend_instdir }}/build/locales/{{ item.language }}"
    state: directory
    owner: "{{ oerindex_frontend_owner }}"
    group: "{{ oerindex_frontend_group }}"
  loop: '{{ oerindex_frontend_custom_translations | default([], true) }}'

- name: Copy custom translations
  copy:
    src: '{{ item.path }}'
    dest: '{{ oerindex_frontend_instdir }}/build/locales/{{ item.language }}/{{ item.path | basename }}'
    owner: "{{ oerindex_frontend_owner }}"
    group: "{{ oerindex_frontend_group }}"
  loop: '{{ oerindex_frontend_custom_translations | default([], true) }}'
  
- name: Ensures the folder for the custom footer  exists 
  file:
    path: "{{ oerindex_frontend_instdir }}/build/footer/{{ item.language }}"
    state: directory
    owner: "{{ oerindex_frontend_owner }}"
    group: "{{ oerindex_frontend_group }}"
  loop: '{{ oerindex_frontend_custom_footers | default([], true) }}'

- name: Copy custom footers 
  copy:
    src: '{{ item.path }}'
    dest: '{{ oerindex_frontend_instdir }}/build/footer/{{ item.language }}/{{ item.path | basename }}'
    owner: "{{ oerindex_frontend_owner }}"
    group: "{{ oerindex_frontend_group }}"
  loop: '{{ oerindex_frontend_custom_footers | default([], true) }}'

- name: Ensures the folder for the custom files exists
  file:
    path: "{{ oerindex_frontend_instdir }}/build/{{ item.destination | dirname }}"
    state: directory
    owner: "{{ oerindex_frontend_owner }}"
    group: "{{ oerindex_frontend_group }}"
  loop: '{{ oerindex_frontend_custom_files | default([], true) }}'

- name: Copy custom files
  copy:
    src: '{{ item.source }}'
    dest: '{{ oerindex_frontend_instdir }}/build/{{ item.destination}}'
    owner: "{{ oerindex_frontend_owner }}"
    group: "{{ oerindex_frontend_group }}"
  loop: '{{ oerindex_frontend_custom_files | default([], true) }}'
