---
- name: Ensures inst-dir exists
  become: true
  file:
    path: "{{ oerindex_frontend_instdir }}"
    owner: "{{ oerindex_frontend_owner }}"
    group: "{{ oerindex_frontend_group }}"
    state: directory
    recurse: true # migration from old usage of ownership - migrate old files

- name: download OER search index frontend
  become: true
  get_url:
    url: "{{ oerindex_frontend_artifact_url }}"
    force: yes
    dest: "{{ oerindex_frontend_instdir }}/frontend.zip"
    owner: "{{ oerindex_frontend_owner }}"
    group: "{{ oerindex_frontend_group }}"

- name: Ensure unzip is present
  become: true
  package:
    name: ["unzip"]

- name: extract OER search index frontend
  become: true
  unarchive:
    remote_src: yes
    src: '{{ oerindex_frontend_instdir }}/frontend.zip'
    dest: "{{ oerindex_frontend_instdir }}"
    owner: "{{ oerindex_frontend_owner }}"
    group: "{{ oerindex_frontend_group }}"

- name: Add configuration file.
  become: true
  template:
    src: "config.js"
    dest: '{{ oerindex_frontend_public_dir }}/config/config.js'
    owner: "{{ oerindex_frontend_owner }}"
    group: "{{ oerindex_frontend_group }}"

- include_tasks: common-config.yml
- include_tasks: sitemap.yml
