---
# Playbook: Installation of oersi-frontend module
- hosts: all
  roles:
    - init-facts

- hosts: all
  roles:
    - role: geerlingguy.docker
      become: yes
      vars:
        docker_users:
          - "{{ oersi_user }}"
      when: oerindex_frontend_features_use_ssr

- hosts: all
  roles:
    - oer-search-index-frontend
