---
# Playbook: provisioning of third party software that is required for oersi
- hosts: all
  roles:
    - init-facts
    - index-scripts

- hosts: all
  become: yes
  roles:
    - set-timezone
  tags:
    - root-task

- hosts: all
  become: yes
  roles:
    - java
    - elasticsearch

- hosts: all
  roles:
    - tomcat
    - thumbnails

- hosts: all
  become: yes
  roles:
    - nginx
    - role: kibana
      when: kibana_install
    - role: mariadb
      tags: matomo
      when: matomo_install
    - role: matomo
      tags: matomo
      when: matomo_install
