---
oerindex_frontend_i18n_cache_expiration: 600000 # expiration time of the i18n translation cache storage
oerindex_frontend_i18n_debug: "false"
oerindex_frontend_track_total_hits: "true" # track number of total hits from elasticsearch - see https://www.elastic.co/guide/en/elasticsearch/reference/7.10/search-your-data.html#track-total-hits
oerindex_frontend_header_logo_url: "" # if set, use this URL for the logo in the header and include your custom svg or similar; default is "logo-192.png". You may use placeholders {{dark}} and {{small}} to use different logo-versions for dark/mobile mode (they will be replaced by "_dark" and "_small").
oerindex_frontend_theme_colors: "null" # customize colors of the theme; format: {primary: {main: "#000"}, secondary: {main: "#000"}}
oerindex_frontend_theme_colors_dark: "null" # customize colors of the dark theme; format: {primary: {main: "#000"}, secondary: {main: "#000"}}

oerindex_frontend_features_dark_mode: "false"
oerindex_frontend_features_embed_oer: "true"
oerindex_frontend_features_scroll_top_button: "true"
