---
oerindex_frontend_i18n_cache_expiration: 600000 # expiration time of the i18n translation cache storage
oerindex_frontend_i18n_debug: "false"
oerindex_frontend_track_total_hits: "true" # track number of total hits from elasticsearch - see https://www.elastic.co/guide/en/elasticsearch/reference/7.10/search-your-data.html#track-total-hits
oerindex_frontend_header_logo_url: "" # if set, use this URL for the logo in the header and include your custom svg or similar; default is "logo-192.png". You may use placeholders {{dark}} and {{small}} to use different logo-versions for dark/mobile mode (they will be replaced by "_dark" and "_small").
oerindex_frontend_theme_colors: "" # customize colors of the theme; format: {primary: {main: "#000"}, secondary: {main: "#000"}}
oerindex_frontend_theme_colors_dark: "" # customize colors of the dark theme; format: {primary: {main: "#000"}, secondary: {main: "#000"}}

oerindex_frontend_features_dark_mode: "true"
oerindex_frontend_features_change_font_size: "false"
oerindex_frontend_features_embed_oer: "true"
oerindex_frontend_features_oersi_thumbnails: "{{ 'true' if oerindex_features_generate_thumbnails else 'false' }}"
oerindex_frontend_features_scroll_top_button: "true"

oerindex_frontend_ssr_repo_url: https://gitlab.com/oersi/oersi-frontend.git
oerindex_frontend_ssr_repo_version: minimal-nextjs-example

oerindex_frontend_owner: "{{ oersi_user }}"
oerindex_frontend_group: "{{ oersi_user if oerindex_frontend_features_use_ssr else 'www-data' }}"

oerindex_frontend_hierarchical_vocab_filters: # the vocab-scheme files will be updated from the backend periodically
  - vocabName: hochschulfaechersystematik
oerindex_frontend_vocab_scheme_update_schedule_hour: "22"

search_index_frontend_field_configuration:  # see Frontend-Readme -> General field configuration
  baseFields:
    title: name
    resourceLink: id
    licenseUrl: license.id
    author: creator.name
    thumbnailUrl: image
    description: description
    keywords: keywords
  embedding:
    mediaUrl: trailer.embedUrl
    fallbackMediaUrl:
      - encoding.embedUrl
  options:
    - dataField: about.id
      isHierarchicalConcept: true
      schemeParentMap: /vocabs/hochschulfaechersystematik-parentMap.json
      translationNamespace: labelledConcept
    - dataField: audience.id
      translationNamespace: labelledConcept
    - dataField: conditionsOfAccess.id
      translationNamespace: labelledConcept
    - dataField: inLanguage
      translationNamespace: language
    - dataField: learningResourceType.id
      translationNamespace: labelledConcept
    - dataField: license.id
      defaultDisplayType: licenseGroup

search_index_frontend_search_configuration:  # see Frontend-Readme -> Search configuration
  searchField:
    dataField:
      - name
      - creator.name
      - description
      - keywords
      - about.prefLabel_full
      - learningResourceType.prefLabel_full
    fieldWeights:
      - 1
      - 3
  filters:
    - componentId: about
      dataField: about.id
      showSearch: true
      allowedSearchRegex: ^[\u00C0-\u017Fa-zA-Z .-]*$
      size: 1000
    - componentId: learningResourceType
      dataField: learningResourceType.id
    - componentId: license
      dataField: license.id
      prefixAggregationQueryPrefixes:
        - https://creativecommons.org/licenses/by/
        - https://creativecommons.org/licenses/by-sa/
        - https://creativecommons.org/licenses/by-nd/
        - https://creativecommons.org/licenses/by-nc-sa/
        - https://creativecommons.org/licenses/by-nc/
        - https://creativecommons.org/licenses/by-nc-nd/
        - https://creativecommons.org/publicdomain/zero/
        - https://creativecommons.org/publicdomain/mark
        - https://www.apache.org/licenses/LICENSE-2.0
        - https://www.gnu.org/licenses/fdl
        - https://www.gnu.org/licenses/gpl
      prefixAggregationQueryAdditions:
        - value: "https:/"
          replacement: "http:/"
    - componentId: author
      dataField: persons.name.keyword
      labelKey: creator.name
      showSearch: true
      reloadFilterOnSearchTermChange: true
      allowedSearchRegex: ^[\u00C0-\u017Fa-zA-Z .-]*$
      size: 1000
    - componentId: sourceOrganization
      dataField: institutions.name
      labelKey: sourceOrganization.name
      showSearch: true
      reloadFilterOnSearchTermChange: true
      size: 1000
    - componentId: language
      dataField: inLanguage
    - componentId: provider
      dataField: mainEntityOfPage.provider.name
      showSearch: true

search_index_frontend_result_card_configuration:  # see Frontend-Readme -> Result Card configuration
  subtitle:
    field: creator.name
  content:
    - field: description
      maxLines: 4
      bold: true
      fallback:
        - keywords
    - field: about.id
    - field: learningResourceType.id

search_index_frontend_detail_page_configuration:  # see Frontend-Readme -> Detail page configuration
  content:
    - field: creator.name
    - field: description
    - field: about.id
    - field: learningResourceType.id
    - field: sourceOrganization.name
    - field: publisher.name
    - field: datePublished
      type: date
    - field: inLanguage
    - field: keywords
      type: chips
    - field: license.id
      type: license
    - field: audience.id
    - field: mainEntityOfPage.provider.name
      type: link
      externalLinkField: mainEntityOfPage.id

search_index_frontend_embedded_structured_data_adjustments:  # see Frontend-Readme -> Embedded structured data adjustments
  - fieldName: "@context"
    action: replace
    value: https://schema.org/
