---
# protoyp von https://github.com/sroertgen/oerhoernchen20_docker bzw https://github.com/programmieraffe/oerhoernchen20
# -> für erste Tests mit dem Prototyp ok, sollte später jedoch anders gelöst werden, siehe https://gitlab.com/TIBHannover/oer/oersi-metadata-harvester

- name: Install Python3
  become: yes
  package:
    name: [ "python3", "python3-venv" ]
    state: present
  tags:
  - root-task

# Problem with windows and copy-module -> use archive, should be moved to a separate project anyway
- name: Ensures inst-dir exists
  file: path='{{ oerindex_harvester_instdir }}' state=directory

- name: Copy OER metadata harvester
  copy:
    src: oer_scrapy/
    dest: "{{ oerindex_harvester_instdir }}/"
    mode: 'preserve'

- name: Fix line endings for installer
  command:
    cmd: "sed -i 's/\r$//' install.sh"
    chdir: '{{ oerindex_harvester_instdir }}'

- name: Fix line endings for importer
  command:
    cmd: "sed -i 's/\r$//' import.sh"
    chdir: '{{ oerindex_harvester_instdir }}'

- name: Install OER metadata harvester
  command:
    cmd: '{{ oerindex_harvester_instdir }}/install.sh'
    chdir: '{{ oerindex_harvester_instdir }}'

- name: Configure cron schedule - scrapy import OER sources
  cron:
    name: "Scrapy Import OER sources"
    hour: '{{ (oerindex_import_sources_schedule_hour | int) + 2 }}'
    minute: '{{ oerindex_import_sources_schedule_minute }}'
    job: 'cd {{ oerindex_harvester_instdir }} && {{ oerindex_harvester_instdir }}/import.sh digill hhu hoou oncampus oerinfo tibav &> {{ oerindex_harvester_instdir }}/scrapy.log'
    state: '{{ oerindex_import_sources_schedule_state }}'
