---
# Playbook: provisioning of third party software that is required for oersi
- hosts: all
  roles:
    - init-facts
    - index-scripts

- hosts: all
  become: yes
  roles:
    - set-timezone
  tags:
    - root-task

- hosts: oerindex
  become: yes
  roles:
    - mariadb
    - geerlingguy.java
    - elasticsearch
    - logstash
    - role: kibana
      when: kibana_install

- hosts: oerindex
  roles:
    - tomcat

- hosts: oerindex
  become: yes
  roles:
    - nginx
    - role: matomo
      tags: matomo
      when: matomo_install
