---
- include_tasks: tool.yml
  when: internationalization_tool_install

- name: Configure cron schedule - process translation of OERSI keywords
  cron:
    name: "Process translation of OERSI keywords via internationalization-tool"
    hour: "{{ internationalization_tool_oersi_keyword_translation_schedule_hour }}"
    minute: "{{ internationalization_tool_oersi_keyword_translation_schedule_minute }}"
    job: "cd {{ internationalization_tool_dir }} && python3 -m internationalization.oersi.KeywordTranslator"
    state: "{{ 'present' if internationalization_tool_install else 'absent' }}"

- name: Configure cron schedule - create synonym file for translated keywords
  cron:
    name: "Create synonym file for translated keywords via internationalization-tool"
    hour: "{{ internationalization_tool_oersi_synonym_creation_schedule_hour }}"
    minute: "{{ internationalization_tool_oersi_synonym_creation_translation_schedule_minute }}"
    job: "{{ base_dir }}/bin/create-synonyms-file.sh > {{ base_dir }}/log/create-synonyms-file.log 2>&1"
    state: "{{ 'present' if internationalization_tool_install else 'absent' }}"

- include_tasks: monitoring.yml
