---
- name: Ensures dirs exist
  file: path='{{ item }}' state=directory
  loop:
    - '{{ internationalization_tool_dir }}'
    - '{{ internationalization_tool_logdir }}'

- name: download internationalization tool
  get_url:
    url: "{{ internationalization_tool_artifact_url }}"
    force: yes
    dest: "{{ internationalization_tool_dir }}/internationalization.zip"

- name: Ensure packages are present
  package:
    name: ["unzip"]
  become: yes

- name: extract internationalization tool
  unarchive:
    remote_src: yes
    src: '{{ internationalization_tool_dir }}/internationalization.zip'
    dest: "{{ internationalization_tool_dir }}"

- name: Ensure python packages are present
  package:
    name: ["python3", "python3-pip"]
  become: yes

- name: install requirements
  command:
    cmd: "pip3 install -r requirements.txt"
    chdir: "{{ internationalization_tool_dir }}"

- name: Create config.yml
  template:
    src: "config.yml.j2"
    dest: "{{ internationalization_tool_dir }}/config/config.yml"
    mode: '600'

- name: Create log4j.properties
  template:
    src: "logging.conf.j2"
    dest: "{{ internationalization_tool_dir }}/config/logging.conf"

