---
- name: Ensure mysql python packages are present
  package:
    name: python-mysqldb
  become: yes
  tags:
  - root-task
  when: ansible_distribution == 'Debian' and ansible_distribution_version <= '10'

- name: Ensure mysql python packages are present
  package:
    name: python3-mysqldb
  become: yes
  tags:
  - root-task
  when: ansible_distribution == 'Debian' and ansible_distribution_version >= '11'

- name: Create a new database
  become: true
  mysql_db:
    name: '{{ matomo_dbname }}'
    encoding: 'utf8'
    collation: 'utf8_bin'
    config_file: /etc/my.cnf.d/mysql.cnf
    state: present

- name: Create database user
  become: true
  mysql_user:
    name: '{{ matomo_dbuser }}'
    password: '{{ matomo_dbpassword }}'
    priv: '{{ matomo_dbname }}.*:ALL'
