---
# Requirements for the matomo role:
# - MariaDB has to be installed
# - nginx has to be installed

- include_tasks: php.yml
- include_tasks: init-database.yml
- include_tasks: matomo.yml
- include_tasks: nginx-config.yml

- name: Check if the config.ini.php exists
  become: true
  stat:
    path: "{{ matomo_inst_dir }}/matomo/config/config.ini.php"
  register: matomo_config_ini_stat_result
        
- include_tasks: matomo-init.yml
  when: not matomo_config_ini_stat_result.stat.exists
