---
- name: create matomo directory
  become: true
  file: 
    path: '{{ matomo_inst_dir }}'
    state: directory
    owner: '{{ matomo_owner }}'
    group: '{{ matomo_group }}'

- name: download matomo
  become: true
  get_url:
    url: "{{ matomo_archive_url }}"
    dest: "{{ matomo_inst_dir }}.zip"
    owner: '{{ matomo_owner }}'
    group: '{{ matomo_group }}'

- name: Ensure unzip is present
  become: true
  package:
    name: [ "unzip" ]

- name: extract matomo
  become: true
  unarchive:
    remote_src: yes
    src: '{{ matomo_inst_dir }}.zip'
    dest: "{{ matomo_inst_dir }}"
    owner: '{{ matomo_owner }}'
    group: '{{ matomo_group }}'
    creates: '{{ matomo_inst_dir }}/matomo'

- include_tasks: geo-ip.yml

- name: Ensures bin dir exists
  become: true
  file: path='{{ matomo_bin }}' state=directory

- name: Add nginx import script
  become: true
  template:
    src: import_nginx_logs.sh
    dest: '{{ matomo_bin }}/import_nginx_logs.sh'
    mode: '744'

- name: Configure cron schedule - analyze nginx access log
  become: true
  cron:
    name: "Matomo import of nginx access log from yesterday"
    hour: '0'
    minute: '1'
    job: '{{ matomo_bin }}/import_nginx_logs.sh'
