---
- name: Adding user to logstash group
  become: yes
  user:
    name: "{{ oersi_user }}"
    groups: logstash
    append: yes

- name: download mariadb jconnector
  get_url:
    url: '{{mariadb_jconnector_url}}'
    dest: "{{ logstash_dir }}/logstash-core/lib/jars/mariadb-connector-java.jar"
    force: yes # necessary for driver updates

- name: Ensure config-directories exist
  file: path={{ item }} state=directory
  with_items:
    - "{{ logstash_settings_dir }}/pipelines/"
    - "{{ logstash_serviced_conf_dir }}/"

- name: Chown of logstash installation
  file:
    path: '{{ logstash_dir }}'
    owner: logstash
    group: logstash
    recurse: yes
    state: directory

- name: Configure Logstash.
  template:
    src: "{{ item }}"
    dest: "{{ logstash_settings_dir }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - logstash.yml
    - pipelines.yml
  notify: restart logstash
  
- name: Configure Logstash pipelines.
  template:
    src: "{{ item }}"
    dest: "{{ logstash_settings_dir }}/pipelines/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 001-input_jdbc_metadata.conf
    - 001-filter_jdbc.conf
    - 001-output_elastic_search.conf
    - 002-deletion.conf
  notify: restart logstash

- name: Add reset-jdbc-lastrun.sh
  template:
    src: "reset-jdbc-lastrun.sh.j2"
    dest: "{{ logstash_dir }}/bin/reset-jdbc-lastrun.sh"
    owner: logstash
    group: logstash
    mode: 0700
    
- name: Add run-oersi-pipeline-once.sh
  template:
    src: "run-oersi-pipeline-once.sh.j2"
    dest: "{{ logstash_dir }}/bin/run-oersi-pipeline-once.sh"
    owner: logstash
    group: logstash
    mode: 0700

- name: Ensure oer_index.conf exists
  copy:
    content: ""
    dest: "{{ base_dir }}/conf/oer_index.conf"
    force: no
    group: "{{ oersi_user }}"
    owner: "{{ oersi_user }}"

- name: Add override.conf of serviced
  template:
    src: "serviced-override.conf.j2"
    dest: "{{ logstash_serviced_conf_dir }}/override.conf"
    mode: 0644
  notify: restart logstash
  register: logstash_systemd_config_result
  
- name: reload systemd
  systemd: daemon_reload=yes
  when: logstash_systemd_config_result.changed

- name: Install sudo
  package:
    name: sudo
    state: present

- name: Allow logstash group to manage logstash service
  become: yes
  template:
    src: "sudoers-logstash.j2"
    dest: "/etc/sudoers.d/logstash"
    mode: 0440
    validate: '/usr/sbin/visudo -cf %s'
