---
- name: download mariadb jconnector
  get_url:
    url: '{{mariadb_jconnector_url}}'
    dest: "{{ logstash_dir }}/logstash-core/lib/jars/mariadb-connector-java.jar"
    force: yes # necessary for driver updates

- name: Ensure config-directories exist
  file: path={{ item }} state=directory
  with_items:
    - /etc/logstash/templates/
    - /etc/logstash/pipelines/

- name: Configure Logstash.
  template:
    src: "{{ item }}"
    dest: "/etc/logstash/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - logstash.yml
    - pipelines.yml
  notify: restart logstash
  
- name: Configure Logstash mapping.
  template:
    src: "mapping.json"
    dest: "/etc/logstash/templates/mapping.json"
    owner: root
    group: root
    mode: 0644
  notify: restart logstash
  
- name: Configure Logstash pipelines.
  template:
    src: "{{ item }}"
    dest: "/etc/logstash/pipelines/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - input_jdbc_metadata.conf
    - filter_jdbc.conf
    - output_elastic_search.conf
  notify: restart logstash

- name: Add reset-jdbc-lastrun.sh
  template:
    src: "reset-jdbc-lastrun.sh.j2"
    dest: "{{ logstash_dir }}/bin/reset-jdbc-lastrun.sh"
    owner: logstash
    group: logstash
    mode: 0700

- name: Install sudo
  package:
    name: sudo
    state: present

- name: Allow logstash group to manage logstash service
  become: yes
  template:
    src: "sudoers-logstash.j2"
    dest: "/etc/sudoers.d/logstash"
    mode: 0440
    validate: 'visudo -cf %s'

- name: Force a restart if configuration has changed.
  meta: flush_handlers
