---
- name: Ensures inst-dir exists
  become: true
  file:
    path: "{{ search_index_schemas_instdir }}"
    owner: "{{ search_index_schemas_owner }}"
    group: "{{ search_index_schemas_group }}"
    state: directory

- name: download search index schema files
  get_url:
    url: "{{ search_index_metadata_schema_artifact_url }}"
    force: yes
    dest: "{{ base_dir }}/metadata-schema.zip"

- name: Ensure packages are present
  become: true
  package:
    name: ["unzip"]

- name: extract search index schema files
  become: true
  unarchive:
    remote_src: yes
    src: '{{ base_dir }}/metadata-schema.zip'
    dest: "{{ search_index_schemas_instdir }}"
    owner: "{{ search_index_schemas_owner }}"
    group: "{{ search_index_schemas_group }}"

- name: Configure nginx.
  become: true
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/schemas.conf
  notify:
    - restart nginx

- name: enable nginx config
  become: true
  file:
    path: '/etc/nginx/sites-enabled/schemas.conf'
    src: '/etc/nginx/sites-available/schemas.conf'
    state: link
  notify:
    - restart nginx

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
